version: '3.1'

services:

  db:
    image: postgres:14.7
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: 'the-loop-challenge'
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin